
name: Java CI-CD with Gradle

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test-build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew clean test :bootstrap-spring:bootJar
    
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      
  release:
    needs: test-build
    
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Get Gradle project version
      id: get_version
      run: |
        VERSION=$(./gradlew -q printVersion) 
        echo "extracted version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Build for release
      run: ./gradlew clean :bootstrap-spring:bootJar

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=${{ steps.get_version.outputs.VERSION }}
          type=sha,prefix=,suffix=,enable=true
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Trigger Dokploy Deployment
      run: |
        RESPONSE=$(curl -sS -X 'POST' \
                 -w "\nHTTP_STATUS:%{http_code}" \
                 '${{ secrets.DOKPLOY_URL }}/api/trpc/application.deploy' \
                 -H 'accept: application/json' \
                 -H 'x-api-key: ${{ secrets.DOKPLOY_AUTH_TOKEN }}' \
                 -H 'Content-Type: application/json' \
                 -d '{"json": {"applicationId": "${{ secrets.DOKPLOY_APPLICATION_ID }}"}}')
                 
        HTTP_STATUS=$(echo "$RESPONSE" | tail -n 1 | sed -e 's/HTTP_STATUS://')
        RESPONSE_BODY=$(echo "$RESPONSE" | head -n -1)
  
        echo "--- Dokploy API Response ---"
        echo "Status: $HTTP_STATUS"
        echo "Body: $RESPONSE_BODY"
        echo "----------------------------"
  
        if [[ "$HTTP_STATUS" -ge 200 && "$HTTP_STATUS" -lt 300 ]]; then
          echo "::notice title=Deployment Triggered::Dokploy deployment successfully triggered (Status $HTTP_STATUS)."
        else
          echo "::error title=Deployment Failed::Dokploy Error. Status $HTTP_STATUS, Response: $RESPONSE_BODY"
          exit 1 # Force GitHub Actions step failure
        fi
